[project]
name = "chatbot_wikipedia_crawler"
version = "0.0.1"
dependencies = [
    "lxml==6.1.1",
    "mwparserfromhell==0.7.2",
    "sentence-transformers==5.5.1",
    "semantic_text_splitter==0.31.0",
    "langchain_text_splitters==0.3.8",
    "psycopg[binary]==3.3.4",
    "pgvector==0.4.2",

    "torch @ https://download.pytorch.org/whl/cu126/torch-2.12.0%2Bcu126-cp314-cp314-win_amd64.whl"
]

[tool.ruff]
line-length = 88
